AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Little Fire Flames - Events API

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 30
    MemorySize: 512
    Environment:
      Variables:
        EVENTS_TABLE_NAME: !Ref EventsTable

Resources:
  # DynamoDB Table for Events
  EventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: little-fire-flames-events
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

  # API Gateway HTTP API
  EventsApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Description: HTTP API for Events
      CorsConfiguration:
        AllowOrigins:
          - "*"
        AllowMethods:
          - GET
          - POST
          - PUT
          - DELETE
          - OPTIONS
        AllowHeaders:
          - "*"
        MaxAge: 300

  # Single Lambda Function for all routes
  EventsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../api
      Handler: dist/handlers/router.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref EventsTable
      Events:
        Api:
          Type: HttpApi
          Properties:
            ApiId: !Ref EventsApi
            Path: /{proxy+}
            Method: ANY

Outputs:
  EventsApiUrl:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${EventsApi}.execute-api.${AWS::Region}.amazonaws.com'
  EventsTableName:
    Description: DynamoDB Table Name
    Value: !Ref EventsTable

