/**
 * Production environment — fallback only.
 * The primary config source is /config.json generated by deploy/scripts/fetch-stack-config.js.
 * These empty values ensure the app fails visibly rather than making requests to placeholder URLs.
 */
export const environment = {
  production: true,
  apiUrl: '',
  cognito: {
    userPoolId: '',
    clientId: '',
    region: '',
  },
};
